### ISSUE TITLE
TomcatFilterMemShellFromJMX兼容性问题

### ISSUE THREAD

**Issue by ab-Alex** [Y4er/ysoserial#2]
Spring-Boot-Version: 2.1.6.RELEASE 注入内存马失败
异常：
Can not set javax.management.MBeanServer field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor to org.apache.tomcat.util.modeler.NoDescriptorRegistry$NoJmxMBeanServer
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/43507436/170728641-83dba2c2-cf3a-4fcd-a4b9-aee204e1313b.png">

**Comment by Y4er** [comment]
用另一个，从thread中获取试试。有的springboot存在这个问题。

**Comment by ab-Alex** [comment]
thread可以兼容
